name: deploy

on:
  push:
    branches:
      - main

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Streamlit Cloud redeploys automatically on pushes to main.
